// <auto-generated />
using System;
using GestionGastos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionGastos.Api.Data.Migraciones
{
    [DbContext(typeof(GestionGastosDbContext))]
    [Migration("20260808001516_CrearCategoriasYMovimientos")]
    partial class CrearCategoriasYMovimientos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionGastos.Api.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("EsDelSistema")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaBajaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Tipo");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000001"),
                            EsDelSistema = true,
                            Nombre = "Comida",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000002"),
                            EsDelSistema = true,
                            Nombre = "Transporte",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000003"),
                            EsDelSistema = true,
                            Nombre = "Vivienda",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000004"),
                            EsDelSistema = true,
                            Nombre = "Servicios",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000005"),
                            EsDelSistema = true,
                            Nombre = "Salud",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000006"),
                            EsDelSistema = true,
                            Nombre = "Ocio",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000007"),
                            EsDelSistema = true,
                            Nombre = "Otros",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = new Guid("b2000000-0000-4000-8000-000000000001"),
                            EsDelSistema = true,
                            Nombre = "Sueldo",
                            Tipo = "Ingreso"
                        },
                        new
                        {
                            Id = new Guid("b2000000-0000-4000-8000-000000000002"),
                            EsDelSistema = true,
                            Nombre = "Ingreso extra",
                            Tipo = "Ingreso"
                        },
                        new
                        {
                            Id = new Guid("b2000000-0000-4000-8000-000000000003"),
                            EsDelSistema = true,
                            Nombre = "Otros",
                            Tipo = "Ingreso"
                        });
                });

            modelBuilder.Entity("GestionGastos.Api.Entidades.Movimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId", "Fecha");

                    b.ToTable("Movimientos", (string)null);
                });

            modelBuilder.Entity("GestionGastos.Api.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GestionGastos.Api.Entidades.Categoria", b =>
                {
                    b.HasOne("GestionGastos.Api.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionGastos.Api.Entidades.Movimiento", b =>
                {
                    b.HasOne("GestionGastos.Api.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionGastos.Api.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
